version: '3.4'

networks:
    nt.realestate:

services:
    sql.server:
        image: mcr.microsoft.com/mssql/server
        environment:
            SA_PASSWORD: SebasCaro454
            ACCEPT_EULA: "Y"
        ports:
            - "8004:1433"
        volumes:
            - db-data:/var/opt/mssql
        networks:
            - nt.realestate
    realestate.api:
        image: ${DOCKER_REGISTRY-}realestateapi
        build:
            context: .
            dockerfile: RealEstate.API/Dockerfile
        ports:
            - "8003:80"
        depends_on:
            - sql.server
        environment:
            - DB_ConnectionString=Data Source=sql.server;Initial Catalog=RealEstate;User ID=sa;Password=SebasCaro454;TrustServerCertificate=True;
            - Azure_StorageConnectionString=DefaultEndpointsProtocol=https;AccountName=realestateatest;AccountKey=obkWsTxYiEl+cj78D0WgvAVEc1pE7AbAjhx2nqGuJ+CDWhFB999QwJKlq+JHexee9xrf9z2/IMGh+ASt4oBNmA==;EndpointSuffix=core.windows.net
        networks:
            - nt.realestate
volumes:
    db-data:
